/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIReferences */

#ifndef _Included_JNIReferences
#define _Included_JNIReferences
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIReferences
 * Method:    getFooIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_JNIReferences_getFooIntegerObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNIReferences
 * Method:    getBarIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_JNIReferences_getBarIntegerObject
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
