/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIInstance */

#ifndef _Included_JNIInstance
#define _Included_JNIInstance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIInstance
 * Method:    modifyInstanceVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIInstance_modifyInstanceVariable
  (JNIEnv *, jobject);

/*
 * Class:     JNIInstance
 * Method:    modifyStaticVariable
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIInstance_modifyStaticVariable
  (JNIEnv *, jobject);

/*
 * Class:     JNIInstance
 * Method:    nativeMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIInstance_nativeMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
