/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIObjArray */

#ifndef _Included_JNIObjArray
#define _Included_JNIObjArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIObjArray
 * Method:    getIntegerObject
 * Signature: (I)Ljava/lang/Integer;
 */
JNIEXPORT jobject JNICALL Java_JNIObjArray_getIntegerObject
  (JNIEnv *, jobject, jint);

/*
 * Class:     JNIObjArray
 * Method:    sumAndAverage
 * Signature: ([Ljava/lang/Integer;)[Ljava/lang/Double;
 */
JNIEXPORT jobjectArray JNICALL Java_JNIObjArray_sumAndAverage
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
