/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIPrimitive */

#ifndef _Included_JNIPrimitive
#define _Included_JNIPrimitive
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIPrimitive
 * Method:    average
 * Signature: (II)D
 */
JNIEXPORT jdouble JNICALL Java_JNIPrimitive_average
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     JNIPrimitive
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_JNIPrimitive_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     JNIPrimitive
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_JNIPrimitive_sumAndAverage
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
